// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUO_VYLQ0DOCLFhprhWLPYAvJTCAxMj0U',
    appId: '1:955122523159:web:b379df494e46e6cbac5052',
    messagingSenderId: '955122523159',
    projectId: 'moviles-30e5d',
    authDomain: 'moviles-30e5d.firebaseapp.com',
    storageBucket: 'moviles-30e5d.appspot.com',
    measurementId: 'G-CYMVXW8GS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1IUvzCv_BuUOcc6ftqQDIL_livZqt40A',
    appId: '1:955122523159:android:ebdcc39581cb99f8ac5052',
    messagingSenderId: '955122523159',
    projectId: 'moviles-30e5d',
    storageBucket: 'moviles-30e5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUSgdtoerZ6MXcE4Ga2J1F6ps0t6ALX34',
    appId: '1:955122523159:ios:2b3a69e790630cddac5052',
    messagingSenderId: '955122523159',
    projectId: 'moviles-30e5d',
    storageBucket: 'moviles-30e5d.appspot.com',
    iosBundleId: 'com.example.autos',
  );
}
